### ISSUE TITLE
AttributeError: 'Module' object has no attribute '_obj'

### ISSUE THREAD

**Issue by axil** [pytest-dev/pytest#1944]
pytest generates an exception which is hard to understand:

    % uname -a
    Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux

    % cat test.py
    def f():
        return
    
    assert f() == 10

    % pytest test.py
    platform linux -- Python 3.4.2, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
    ___________________________ ERROR collecting test.py _____________________________
    env/lib/python3.4/site-packages/_pytest/python.py:209: in fget
        return self._obj
    E   AttributeError: 'Module' object has no attribute '_obj'

Seems to be the same issue as mentioned here:
https://github.com/pytest-dev/pytest-django/issues/386

**Comment by axil** [comment]
The same works with Python 2.7.9 (no AttributeError)

**Comment by The-Compiler** [comment]
This is the full output:

```
_______________________ ERROR collecting test.py _______________________
/usr/lib/python3.5/site-packages/_pytest/python.py:209: in fget
    return self._obj
E   AttributeError: 'Module' object has no attribute '_obj'

During handling of the above exception, another exception occurred:
test.py:4: in <module>
    assert f() == 10
E   assert None == 10
E    +  where None = <function f at 0x7fada7dd11e0>()
!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!
```

the upper part is probably caused by Python 3's chained exception support and #1486.

**Comment by axil** [comment]
Not something really universal, but this patch fixes the issue.

**Comment by nicoddemus** [comment]
Resolved in `master`
