### ISSUE TITLE
ConftestImportFailure in python 3.4 (can't repro on python 3.5)

### ISSUE THREAD

**Issue by cbdelavenne** [pytest-dev/pytest#1449]
A bit hard to describe the error, but I have two virtual environments set up. On py3.5.1, the tests run fine, but on py3.4.4 it fails with the stack trace below (both Mac OS X 10.11, Windows 10 and Windows 7).

I tried both pytest versions:

- pytest 2.8.5
- pytest 2.9.0

Is there anything that jumps at you from the stack trace below?
```
/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support --client 127.0.0.1 --port 53430 --file "/Applications/PyCharm CE.app/Contents/helpers/pycharm/pytestrunner.py" -p pytest_teamcity /Users/cbdelavenne/workspace/git/LANDR.QA/testcases/frontend/authentication_test.py --environment dev_en --testrunner mac
Testing started at 11:09 AM ...
pydev debugger: process 80418 is connecting

Connected to pydev debugger (build 143.1919)
Traceback (most recent call last):
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 282, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/cbdelavenne/workspace/git/LANDR.QA/testcases/frontend/authentication_test.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 282, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/cbdelavenne/workspace/git/LANDR.QA/testcases/frontend')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 313, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/cbdelavenne/workspace/git/LANDR.QA/testcases/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 319, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/Users/cbdelavenne/workspace/git/LANDR.QA/testcases/conftest.py", line 19, in <module>
    from lib.constants import ACCESS_KEYS
  File "/Users/cbdelavenne/workspace/git/LANDR.QA/lib/constants.py", line 16, in <module>
    from lib.toolbox import project_root
  File "/Users/cbdelavenne/workspace/git/LANDR.QA/lib/toolbox.py", line 20, in <module>
    from lib import constants
ImportError: cannot import name 'constants'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/pytestrunner.py", line 60, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pycharm/pytestrunner.py", line 34, in main
    pluginmanager=_pluginmanager, args=args)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 852, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 957, in parse
    self._preparse(args)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 928, in _preparse
    args=args, parser=self._parser)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
    return call_outcome.get_result()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 278, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 898, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 265, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 271, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 285, in _getconftestmodules
    clist = self._getconftestmodules(path.dirpath())
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 296, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/Users/cbdelavenne/.virtualenvs/py3.4-LANDR.QA/lib/python3.4/site-packages/_pytest/config.py", line 321, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
_pytest.config.ConftestImportFailure: (local('/Users/cbdelavenne/workspace/git/LANDR.QA/testcases/conftest.py'), (<class 'ImportError'>, ImportError("cannot import name 'constants'",), <traceback object at 0x1064c0788>))
```

`pip list` output for venv py 3.4.4:
```
apipkg (1.4)
awscli (1.10.10)
boto3 (1.2.6)
botocore (1.4.1)
browsermob-proxy (0.7.1)
certifi (2016.2.28)
colorama (0.3.7)
docutils (0.12)
execnet (1.4.1)
fake-factory (0.5.6)
Jinja2 (2.8)
jmespath (0.9.0)
landr (1.2.58)
MarkupSafe (0.23)
pip (8.1.0)
psutil (4.0.0)
py (1.4.31)
pyasn1 (0.1.9)
pytest (2.8.5)
pytest-xdist (1.14)
python-dateutil (2.5.0)
pytz (2015.7)
requests (2.9.1)
rsa (3.3)
s3transfer (0.0.1)
selenium (2.48.0)
setuptools (20.2.2)
six (1.10.0)
teamcity-messages (1.17)
urllib3 (1.14)
wheel (0.29.0)
```

`pip list` output for venv py 3.5.1:
```
apipkg (1.4)
awscli (1.10.10)
boto3 (1.2.6)
botocore (1.4.1)
browsermob-proxy (0.7.1)
certifi (2016.2.28)
colorama (0.3.7)
docutils (0.12)
execnet (1.4.1)
fake-factory (0.5.6)
Jinja2 (2.8)
jmespath (0.9.0)
landr (1.2.58)
MarkupSafe (0.23)
pip (8.1.0)
psutil (4.0.0)
py (1.4.31)
pyasn1 (0.1.9)
pytest (2.8.5)
pytest-xdist (1.14)
python-dateutil (2.5.0)
pytz (2015.7)
requests (2.9.1)
rsa (3.3)
s3transfer (0.0.1)
selenium (2.48.0)
setuptools (20.2.2)
six (1.10.0)
teamcity-messages (1.17)
urllib3 (1.14)
wheel (0.29.0)
```

Is something different in the way _importconftest works on Python 3.4 vs 3.5?

**Comment by The-Compiler** [comment]
You have a circular import of `lib.constants` there:

```
  File "/Users/cbdelavenne/workspace/git/LANDR.QA/testcases/conftest.py", line 19, in <module>
    from lib.constants import ACCESS_KEYS
  File "/Users/cbdelavenne/workspace/git/LANDR.QA/lib/constants.py", line 16, in <module>
    from lib.toolbox import project_root
  File "/Users/cbdelavenne/workspace/git/LANDR.QA/lib/toolbox.py", line 20, in <module>
    from lib import constants
ImportError: cannot import name 'constants'
```

You should be able to reproduce this by doing `from lib.constants import ACCESS_KEYS` outside of pytest too.

Python 3.5 handles those circular imports better in some situations: [issue17636](https://bugs.python.org/issue17636)

**Comment by cbdelavenne** [comment]
You were right. I resolved my issue by fixing the circular imports (refactoring some functions out to different modules).

Thank you for pointing that out.
