### ISSUE TITLE
AttributeError: module 'py' has no attribute 'builtin'

### ISSUE THREAD

**Issue by bfortuner** [pytest-dev/pytest#3618]
Installation of pytest not working on Ubuntu 14.04 with python 3.6.2. I tried installing pytest with both my OS's vanilla python install and a pyenv virtual install.

Traceback (most recent call last):
  File "/home/bfortuner/.pyenv/versions/3.6.2/bin/pytest", line 7, in <module>
    from pytest import main
  File "/home/bfortuner/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pytest.py", line 10, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/home/bfortuner/.pyenv/versions/3.6.2/lib/python3.6/site-packages/_pytest/fixtures.py", line 12, in <module>
    from py._code.code import FormattedExcinfo
  File "/home/bfortuner/.pyenv/versions/3.6.2/lib/python3.6/site-packages/py/_code/code.py", line 7, in <module>
    reprlib = py.builtin._tryimport('repr', 'reprlib')
AttributeError: module 'py' has no attribute 'builtin'

Output of `pip freeze`:

```
atomicwrites==1.1.5
attrs==18.1.0
certifi==2018.4.16
more-itertools==4.2.0
pipenv==2018.6.25
pluggy==0.6.0
six==1.11.0
virtualenv==16.0.0
virtualenv-clone==0.3.0
```

**Comment by pytestbot** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/pytest-dev/pytest/issues/448 (pytest-xdist: AttributeError: 'module' object has no attribute '__all__'), https://github.com/pytest-dev/pytest/issues/1161 (AttributeError: 'module' object has no attribute 'epoll'), https://github.com/pytest-dev/pytest/issues/1447 (AttributeError: 'OutputWriter' object has no attribute 'isatty'), https://github.com/pytest-dev/pytest/issues/555 (AttributeError: '_io.FileIO' object has no attribute 'errors'), and https://github.com/pytest-dev/pytest/issues/1944 (AttributeError: 'Module' object has no attribute '_obj').

**Comment by hanzhuoran** [comment]
Could you elaborate what you did to fix this? 
I have encountered the same problem on pytest.

**Comment by RonnyPfannschmidt** [comment]
removal of the conflicting "py" module
