### ISSUE TITLE
Getting error:  AttributeError: 'Tests' object has no attribute 't'

### ISSUE THREAD

**Issue by vipkum2** [pytest-dev/pytest#3869]
I am using below code, It was working fine with pytest version 3.0.4, not working with 3.7.2
Python version: 3.6 on linux

**class Tests(object):**
     @classmethod
     @pytest.fixture(scope='module', autouse=True)
     **def getTestFixture(self, request):**
        self.fixtureIp   = request.config.getoption('--fixtureIp')
        print()
        print('Fixture IP           : %s' % (self.fixtureIp))
        # Connect to the NE
        self.t = OpenRoadmTest(self.fixtureIp)
        self.t.connectTL1()
        print(self.t) #working fine

    **def test00_getStartingConfig(self,):**
        print(self.t)
        #not working , showing error: AttributeError: 'Tests' object has no attribute 't'

**Comment by RonnyPfannschmidt** [comment]
switching the order of classmethod and fixture should fix the issue for you

**Comment by RonnyPfannschmidt** [comment]
this is a known issue that got introduced by a warning functionality in 3.7 and demonstrates to be __hard__

**Comment by vipkum2** [comment]
Thank you very much for quick response.

**Comment by vipkum2** [comment]
Hi,
Again observed the same issue with pytest version 4.4.1. And this time switching the order is also not working as @RonnyPfannschmidt suggested previously.

**Comment by nicoddemus** [comment]
Hi @vipkum2,

Usually in this case it is enough to set your attribute in the class itself rather than using a `classmethod`. Using your previous example:

```python
class Tests(object):
     @pytest.fixture(scope='module', autouse=True)
     def getTestFixture(self, request):
        ...
        type(self).t = OpenRoadmTest(self.fixtureIp)
        ...
```

This should definitely work. If not, can you post another issue including an example? Thanks!

**Comment by vahabrat** [comment]
> Hi @vipkum2,
> 
> Usually in this case it is enough to set your attribute in the class itself rather than using a `classmethod`. Using your previous example:
> 
> ```python
> class Tests(object):
>      @pytest.fixture(scope='module', autouse=True)
>      def getTestFixture(self, request):
>         ...
>         type(self).t = OpenRoadmTest(self.fixtureIp)
>         ...
> ```
> 
> This should definitely work. If not, can you post another issue including an example? Thanks!
type(self).t = 'some data' completely enough
to get this attribute in methods use:  type(self).t

**Comment by vahabrat** [comment]
Hi @vipkum2!

type(self).t = 'some data' worked for me
to get this value from the attribute in methods use: type(self).t
