### ISSUE TITLE
Pytest 8.1.0 AttributeError: 'NoneType' object has no attribute 'setup_method' with staticmethod test

### ISSUE THREAD

**Issue by anilbey** [pytest-dev/pytest#12065]
Hi, the code that was working fine with pytest==8.0.2 started giving the error below for pytest==8.1.0.

Logs with pytest 8.0.2: https://github.com/BlueBrain/BlueCelluLab/actions/runs/8114860416/job/22181464420
Logs with pytest 8.1.0: https://github.com/BlueBrain/BlueCelluLab/actions/runs/8138274377/job/22239015810?pr=142

```
  request = <SubRequest '_xunit_setup_method_fixture_TestSonataSimulationAccess' for <Function test_init_file_not_found>>
  
      def xunit_setup_method_fixture(request) -> Generator[None, None, None]:
          instance = request.instance
          method = request.function
          if setup_method is not None:
  >           func = getattr(instance, setup_name)
  E           AttributeError: 'NoneType' object has no attribute 'setup_method'
  
  lib/python3.11/site-packages/_pytest/python.py:844: AttributeError
```
All of the installed dependencies and the system versions are available in the CI logs.

**Comment by bluetech** [comment]
I see the failing test is a staticmethod:

https://github.com/BlueBrain/BlueCelluLab/blob/b8330e24c65219f48f0689cdc2d31b579586fb12/tests/test_circuit/test_simulation_access.py#L49-L50

I'm not sure if that's supposed to work (will check later), but curious if there's a particular reason you made it staticmethod?

**Comment by anilbey** [comment]
Oh, thanks. No, in fact that does not have to be a staticmethod. Let me remove that and test again.

**Comment by anilbey** [comment]
There exists another CI workflow (named "Examples") that is also passing on 8.0.2 and failing with 8.1.0. That does not use staticmethod.

8.0.2 Examples CI: https://github.com/BlueBrain/BlueCelluLab/actions/runs/8114860416/job/22181463086
8.1.0 Examples CI: https://github.com/BlueBrain/BlueCelluLab/actions/runs/8138274377/job/22239014458

**Comment by bluetech** [comment]
@anilbey This is a different issue, the `nbmake` plugin will need to update its `pytest_collect_file` hookimpl to be compatible with pytest 8.1.

**Comment by anilbey** [comment]
Update: removing @staticmethod worked.

Great, thanks a lot @bluetech for your quick reply in clarifying the issues.

**Comment by bluetech** [comment]
Bisected to c8792bd0800b8ffc536a6ce251f9eb3075b5f5fa (pr #11780).

We're talking about this reproduction:

```py
class TestIt:
    def setup_method(self): pass

    @staticmethod
    def test_1(): pass
```

This brings up the question, what is `self` in the `setup_method` of a `staticmethod` (or `classmethod`)?

The expectation, as happens with e.g. unittest and regular methods, is that it's a fresh instance.

However, pytest<=8.0 has a subtle bug: all of the static/classmethods use a shared instance. The two prints here are the same:

```py
class TestIt:
    def setup_method(self): print('\nSETUP!', self)

    @staticmethod
    def test_1(): pass

    @classmethod
    def test_2(cls): pass
```

I think that fixing this preexisting bug will also fix the 8.1.0 crash, so I will look into it, though it probably won't be a simple fix, so I might instead restore the previous (problematic) behavior.
