### ISSUE TITLE
[prerelease] Attributes from legacypath plugin added too late?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#9396]
Based on https://github.com/joeyespo/pytest-watch/issues/122 it seems impossible to access `config.inifile` from `pytest_cmdline_main` now.

Minimal reproducer `conftest.py`:

```python
def pytest_cmdline_main(config):
    print(config.inifile)
```

fails after 84722a7904af41191165dcb5458eb641fd2c4d8b with:

```pytb
[...]
  File ".../conftest.py", line 2, in pytest_cmdline_main
    print(config.inifile)
AttributeError: 'Config' object has no attribute 'inifile'
```

but works fine before.

This is part of [Add legacypath plugin, move py.path stuff there by bluetech · Pull Request #9208 · pytest-dev/pytest](https://github.com/pytest-dev/pytest/pull/9208), cc @bluetech.

Makes me wonder whether this plugin is really a good idea in practice, also seeing things like 663be09723e072be48ffba3fd3f9b4991dcb10c3. Maybe those should be kept in core after all until we can deprecate and remove them, and only then be moved to a (rather hackish) plugin?

**Comment by nicoddemus** [comment]
> Makes me wonder whether this plugin is really a good idea in practice

I particularly think so; it would be surprising such a change would work flawlessly from the get go, I believe we just need to iron out the last details.

**Comment by RonnyPfannschmidt** [comment]
we might want to use the plugin_registred hook to do some of the adjustments

**Comment by nicoddemus** [comment]
I'm on this. 👍

**Comment by nicoddemus** [comment]
#9400 is up
