### ISSUE TITLE
Pytest 8.2.0: "AttributeError: 'VendorImporter' object has no attribute 'find_spec'"

### ISSUE THREAD

**Issue by emvollmer** [pytest-dev/pytest#12293]
After updating from pytest 8.1.1 to 8.2.0, previously running tests fail directly with the error message:
```
ImportError while loading conftest '/srv/.../tests/conftest.py'.
AttributeError: 'VendorImporter' object has no attribute 'find_spec'
```
#### Important environment information
OS Linux, 
Python 3.8.10, 
setuptools 44.0.0,
tensorflow 2.10.0,
tensorflow-addons 0.20.0

**Comment by nicoddemus** [comment]
Hi,

Seems related to https://github.com/pypa/setuptools/issues/2104, please try upgrading `setuptools`; 

`44.0.0` is very old (from 2020), the latest one is `69.5.1`.
