### ISSUE TITLE
pytest 8.3.4 --import-mode importlib regression

### ISSUE THREAD

**Issue by alund** [pytest-dev/pytest#13257]
Starting in 8.3.4, running `pytest` using `--import-mode importlib` with the following directory structure no longer works.

```
<root>
    + mypkg
        - pyproject.toml
        + mypkg
            - __init__.py
        + tests
            - test_version.py
```

`test_version.py` attempts to import from `mypkg` and fails:

```
mypkg/tests/version_test.py:1: in <module>
    from mypkg import version
E   ImportError: cannot import name 'version' from 'mypkg' (unknown location)
```

`pytest.ini` contains:
```
[pytest]
addopts = --import-mode importlib
testpaths =
    mypkg/tests
```

`git bisect` says:

```
± git bisect bad
3d3ec5724c6f76bc07d0631ec8061f26f9ecac4c is the first bad commit
commit 3d3ec5724c6f76bc07d0631ec8061f26f9ecac4c
Author: patchback[bot] <45432694+patchback[bot]@users.noreply.github.com>
Date:   Thu Sep 26 01:26:01 2024 +0000

    Fix KeyError with importlib mode (directories with same name) (#12752) (#12843)

    Directories inside a namespace package with the same name as the namespace package would cause a `KeyError` with `--import-mode=importlib`.

    Fixes #12592

    Co-authored-by: Bruno Oliveira <bruno@pytest.org>
    (cherry picked from commit 6486c3f3a858a0c8043f5c3f7c24297b82a0abe4)

    Co-authored-by: dongfangtianyu <7629022+dongfangtianyu@users.noreply.github.com>

 changelog/12592.bugfix.rst |   1 +
 src/_pytest/pathlib.py     | 131 +++++++++++++++++++++++++++++++++------------
 testing/test_pathlib.py    |  74 ++++++++++++++++++++++++-
 3 files changed, 171 insertions(+), 35 deletions(-)
 create mode 100644 changelog/12592.bugfix.rst 
```

I'm attaching a minimal project that should reproduce the problem. 
[reproduce.zip](https://github.com/user-attachments/files/19033172/reproduce.zip)

**Comment by vismaytiwari** [comment]
Opened #14709 for this. Your bisect was spot-on — #12752 made importlib mode eagerly build the parent packages, so with the `mypkg/tests/...` layout pytest binds the outer `mypkg` directory as a namespace package and shadows the real installed `mypkg`, which is why `from mypkg import version` comes back with `(unknown location)`.

The fix defers to the real package when one actually lives inside that directory, so `from mypkg import version` resolves to the installed package again. A test directory named after a stdlib module still gets a namespace package, so the earlier same-name fixes (#12592, #13026) stay intact.

Verified against your `reproduce.zip`: passes on 8.3.3, failing on 8.3.4 and main, passing with the change.
