### PR TITLE
Drop readline workaround introduced in #1281

### LINKED ISSUE #8733: Pytest run fails under Python 3.10.0-beta.2 on Windows
```python-traceback
Traceback (most recent call last):
  ...
  File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\capture.py", line 90, in _readline_workaround
    import readline  # noqa: F401
  File "d:\a\gstore\gstore\.venv\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

<details>
  <summary>full traceback</summary>
  
  ```python-traceback
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.10.0-beta.2\x64\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\hostedtoolcache\windows\Python\3.10.0-beta.2\x64\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "D:\a\gstore\gstore\.venv\Scripts\py.test.exe\__main__.py", line 7, in <module>
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
      code = main()
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\config\__init__.py", line 143, in main
      config = _prepareconfig(args, plugins)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
      config = pluginmanager.hook.pytest_cmdline_parse(
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
      return self._hookexec(self, self.get_hookimpls(), kwargs)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
      return self._inner_hookexec(hook, methods, kwargs)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
      self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
      gen.send(outcome)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
      config: Config = outcome.get_result()
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
      raise ex[1].with_traceback(ex[2])
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
      res = hook_impl.function(*args)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
      self.parse(args)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
      self._preparse(args, addopts=addopts)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\config\__init__.py", line 1191, in _preparse
      self.hook.pytest_load_initial_conftests(
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\hooks.py", line 286, in __call__
      return self._hookexec(self, self.get_hookimpls(), kwargs)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
      return self._inner_hookexec(hook, methods, kwargs)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
      self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
      return outcome.get_result()
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\callers.py", line 80, in get_result
      raise ex[1].with_traceback(ex[2])
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pluggy\callers.py", line 182, in _multicall
      next(gen)  # first yield
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\capture.py", line 157, in pytest_load_initial_conftests
      _readline_workaround()
    File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\capture.py", line 90, in _readline_workaround
      import readline  # noqa: F401
    File "d:\a\gstore\gstore\.venv\lib\site-packages\readline.py", line 34, in <module>
      rl = Readline()
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
      BaseReadline.__init__(self)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
      mode.init_editing_mode(None)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
      self._bind_key('space',       self.self_insert)
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
      if not callable(func):
    File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
      return isinstance(x, collections.Callable)
  AttributeError: module 'collections' has no attribute 'Callable'
  ```
</details>

I discovered this in the [GitHub Actions](https://github.com/sergeyklay/gstore/pull/43/checks?check_run_id=2753902882), with Pytest 6.2.4 on Microsoft Windows Server 2019 and 3.10.0-beta.2 from [actions/setup-python@v2.2.2](https://github.com/actions/setup-python). Unfortunately I don't have a smaller reproducing example than that. Please let me know if I can provide more info.

----

**P.S.** Everything is OK with the same Python and pytest versions on macOs and Linux.

### LINKED ISSUE #8847: Pytest warning on readline
If I use pytest-6.2.4, pytest-cov 2.12.1 and python 3.9.4 on Windows 10

with following commands:

`pytest --cov src --cov-fail-under=98 --cov-report=term-missing`

or simply

`pytest`

I get a warning: 

..\..\app\winpython\python-3.9.4.amd64\lib\site-packages\pyreadline\py3k_compat.py:8
  c:\python_env\app\winpython\python-3.9.4.amd64\lib\site-packages\pyreadline\py3k_compat.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3
, and in 3.10 it will stop working
    return isinstance(x, collections.Callable)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

=> Could please replace pyreadline or somehow hide the warning?

Related: 
https://github.com/pytest-dev/pytest/issues/8733
https://github.com/pyreadline/pyreadline/pull/68

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #8733
Closes #8847

* Also add types-atomicwrites as extras to mypy pre-commit hook (Windows)

### CODE REVIEW

**Comment by nicoddemus** [comment]
As commented in https://github.com/pytest-dev/pytest/issues/8847#issuecomment-873018768:

> Not sure about this. As evident by this issue people still seem to have pyreadline installed, and depending on how obscure the behavior with pyreadline and --pdb is, I'd rather have them see a deprecation warning (making them realize they should probably uninstall pyreadline) than having behavior which is probably much harder to track down.

Fair enough, what do you propose? A warning in Python <=3.9, and skipping it altogether in Python 3.10?

**Comment by The-Compiler** [comment]
> Fair enough, what do you propose? A warning in Python <=3.9, and skipping it altogether in Python 3.10?

Depends on what happens when pdb is invoked on Windows 3.10 with pyreadline installed. If our workaround breaks things (via pyreadline) then skip it; if things are broken anyways (because pdb imports readline), then we might as well keep it as-is.

To me this seems similar to what'd happen if someone created, say, a custom `pathlib.py` shadowing the stdlib one - it's not a situation we should have to consider. But if the workaround breaks things which would work otherwise, then let's get rid of it.

**Comment by nicoddemus** [comment]
> Depends on what happens when pdb is invoked on Windows 3.10 with pyreadline installed.

IIUC it breaks in Python 3.10 with:

```
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

(As per https://github.com/pytest-dev/pytest/issues/8733#issue-912382483).

>  But if the workaround breaks things which would work otherwise, then let's get rid of it.

That was the rationale; and given the workaround was done in 2015 and it was not clear if it was reported in Python 2, it might be the case that dropping it completely is OK.

What do you think?

**Comment by The-Compiler** [comment]
Hm, I see - so with Python 3.10 we'd break pytest entirely if `pyreadline` is installed, and without the workaround, it wouldn't break at all (or only if `--pdb` is used, because I assume that will do `import readline` in pdb?).

How does `--pdb` break without the workaround when pyreadline is installed?

Don't really have a strong opinion on this either way, though.

**Comment by nicoddemus** [comment]
> How does --pdb break without the workaround when pyreadline is installed?

That's described in https://github.com/pytest-dev/pytest/pull/1281, however I don't recall experiencing the problem myself.

**Comment by RonnyPfannschmidt** [comment]
Let's disable the workaround on py 3.10 and schedule the removal to pytest 8

**Comment by nicoddemus** [comment]
> Let's disable the workaround on py 3.10 and schedule the removal to pytest 8

Do we issue a warning for Python <3.9? If so, what should the warning say?

**Comment by RonnyPfannschmidt** [comment]
If pyreadline is involved we should give a hint, im not sure about the exact message

**Comment by nicoddemus** [comment]
Currently pyreadline is involved indirectly:

```
Traceback (most recent call last):
  ...
  File "d:\a\gstore\gstore\.venv\lib\site-packages\_pytest\capture.py", line 90, in _readline_workaround
    import readline  # noqa: F401
  File "d:\a\gstore\gstore\.venv\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "d:\a\gstore\gstore\.venv\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

We import `readline`, which ends up importing `pyreadline` as result.

**Comment by nicoddemus** [comment]
Hi folks, sorry for the delay here. 

Not sure how to proceed... I agree about dropping this for Python 3.10, however what should the warning say for Python<3.9 users? Note that we can't reasonably "warn" or suggest about anything, if we import `readline` and that succeeds, I can't really think of a good warning message. Something like this comes to mind:

> We have a workaround implemented in issue XXX for the readline module, and that's disabled in Python 3.10+. Take a look and comment on the issue if you believe the workaround needs to stay in some form.

But that doesn't seems really helpful or actionable.

**Comment by nicoddemus** [comment]
Gentle ping here. How should we proceed?

**Comment by The-Compiler** [comment]
Given that this is long done, approved and a breaking change, let's sneak it into 7.0.0.
