### ISSUE TITLE
Issue with pytest 8.2.0 and tornado async tests 

### ISSUE THREAD

**Issue by arossert** [pytest-dev/pytest#12263]
I'm using the AsyncHTTPTestCase and AsyncHTTPSTestCase from tornado and the latest pytest fails in collection on this error:
```
Error
collection failure
Stacktrace
usr/local/lib/python3.8/site-packages/tornado/testing.py:180: in __init__
    setattr(self, methodName, _TestMethodWrapper(getattr(self, methodName)))
E   AttributeError: 'AsyncHTTPTestCase' object has no attribute 'runTest'
```

The issue does not exists in 8.1.0

**Comment by bluetech** [comment]
Thanks the report, I will look into it.

**Comment by bluetech** [comment]
- Regressed in 1a5e0eb71d2af0ad113ccd9ee596c7d724d7a4b6

- That commit [relies](https://github.com/pytest-dev/pytest/blob/127a372928cb68e2023ae3c6f8b407c4d2f1f2f7/src/_pytest/unittest.py#L69-L75) on a feature of `unittest.TestCase` where initializing it with the default `methodName="runTest"` is [treated specially](https://github.com/python/cpython/blob/51aefc5bf907ddffaaf083ded0de773adcdf08c8/Lib/unittest/case.py#L419-L426), allowing to instantiate even without `runTest` method actually existing. This is documented under "Changed in Python 3.2" in [unittest.TestCase docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase).

- Tornado [doesn't follow this](https://github.com/tornadoweb/tornado/blob/f399f40fde0ae1b130646db783a6f79cc59231b2/tornado/testing.py#L180), assumes that the methodName exists even with the default. 

My preference would be to fix Tornado, I will try to submit a patch. Otherwise will fix in pytest somehow.

**Comment by bluetech** [comment]
Some projects (like mine) use a common base `TestCase` class. If you do this, you can work around this issue by adding a dummy `runTest` method, like this:

```py
class BaseTestCase(AsyncTestCase):
   # Workaround for https://github.com/pytest-dev/pytest/issues/12263.
   def runTest(self): pass
```

Another workaround, more intrusive but I think harmless and easier, is to drop the following in a `contest.py` file at the root of your testing directory:

```py
from tornado.testing import AsyncTestCase

# Workaround for https://github.com/pytest-dev/pytest/issues/12263.
AsyncTestCase.runTest = lambda self: ...
```

**Comment by bluetech** [comment]
This is fixed in Tornado 6.4.1: https://www.tornadoweb.org/en/stable/releases/v6.4.1.html
