### ISSUE TITLE
Pytest fails on Python3.8rc1

### ISSUE THREAD

**Issue by alexprengere** [pytest-dev/pytest#5909]
I compiled Python3.8rc1 from sources, and ran the [test suite](https://github.com/alexprengere/neobase) of [NeoBase](https://pypi.org/project/NeoBase/), which failed with `ImportError: cannot import name 'MetadataPathFinder' from 'importlib.metadata'`. A few things:
* only the test suite is failing when running `pytest`, otherwise the package is behaving as expected
* I tested previous beta releases of Python3.8 and did not encounter any issues
* the test suite works on Python3.7

Here is the full traceback:
```python
Traceback (most recent call last):
  File "/home/osboxes/Dev/neobase/.env38/bin/py.test", line 10, in <module>
    sys.exit(main())
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 71, in main
    config = _prepareconfig(args, plugins)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 220, in _prepareconfig
    return pluginmanager.hook.pytest_cmdline_parse(
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/pluggy/manager.py", line 83, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 736, in pytest_cmdline_parse
    self.parse(args)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 943, in parse
    self._preparse(args, addopts=addopts)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 885, in _preparse
    self._consider_importhook(args)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 833, in _consider_importhook
    self._mark_plugins_for_rewrite(hook)
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 855, in _mark_plugins_for_rewrite
    for name in _iter_rewritable_modules(package_files):
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 631, in _iter_rewritable_modules
    for fn in package_files:
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 848, in <genexpr>
    package_files = (
  File "/home/osboxes/Dev/neobase/.env38/lib/python3.8/importlib/metadata/__init__.py", line 175, in <genexpr>
    resolver()
  File "<frozen importlib._bootstrap_external>", line 1381, in find_distributions
ImportError: cannot import name 'MetadataPathFinder' from 'importlib.metadata' (/home/osboxes/Dev/neobase/.env38/lib/python3.8/importlib/metadata/__init__.py)
```
I use Fedora 29, compile Python3.8 using the tag `v3.8.0rc1` with optimizations, here is the output of `pip list`:
```
Package        Version Location                 
-------------- ------- -------------------------
atomicwrites   1.3.0   
attrs          19.2.0  
more-itertools 7.2.0   
NeoBase        0.20.1  /home/osboxes/Dev/neobase
packaging      19.2    
pip            19.2.3  
pluggy         0.13.0  
py             1.8.0   
pyparsing      2.4.2   
pytest         5.2.0   
setuptools     41.2.0  
six            1.12.0  
wcwidth        0.1.7   
wheel          0.33.6  
```

**Comment by alexprengere** [comment]
I reproduced the exact same steps using the `v3.8.0b4` tag of CPython, and everything works fine.
`git diff v3.8.0b4..v3.8.0rc1 Lib/importlib/_bootstrap_external.py` on CPython sources shows some changes, but I am unsure if I should open a bug on the Python tracker or not.

I could also reproduce this on other projects, like when running the test suite of this [currency converter](https://pypi.org/project/CurrencyConverter/).

**Comment by asottile** [comment]
did you recreate your python3.8 virtualenv when upgrading from 3.8b4 to 3.8rc1?

**Comment by asottile** [comment]
I ask because I can only reproduce this when reusing a virtualenv created from 3.8b4 or 3.8b3 and then upgrading the system out from underneath the virtualenv (which is not a consistent operation due to the way virtualenvs work)

if I create from scratch it works fine

**Comment by alexprengere** [comment]
Yes, I recreated the virtual environments each time. I tested with both `virtualenv .env -p /usr/local/bin/python3.8` and `/usr/local/bin/python3.8 -m venv .env`, and both failed.

**Comment by asottile** [comment]
does `python3.8 -c 'import importlib.metadata'` reproduce the issue?

can you reproduce in an empty docker? I still suspect done pollution of your installs

**Comment by alexprengere** [comment]
Unfortunately `import importlib.metadata` does not fail, but you are correct that since I have been testing Python3.8 from various sources (compiling from sources, binaries from repos), some pollution *may* be possible, although there was only one Python3.8 in my `$PATH` when I did the tests.

**Comment by asottile** [comment]
how about

```
python3.8 -c 'import importlib.metadata; importlib.metadata.distribution("attrs")'
```

**Comment by alexprengere** [comment]
Indeed, that one fails with the same error regarding `MetadataPathFinder`.

I tried to build CPython `v3.8.0rc1` again from sources, this time using `./configure --prefix` to force a specific location when installing, and everything works fine.

I also tried using the `rc1` binaries from testing with `dnf --enablerepo=updates-testing install python38`, and everything works fine too.

 So either some pollution happened in my installs, or some installation/cleanup is buggy when installing CPython, either way this is not a `pytest` issue, so I will close this.

**Comment by irmen** [comment]
I'm having this exact same issue on Arch Linux with a freshly compiled Python 3.8.0 RC1

**Comment by alexprengere** [comment]
For the record, there was a bug filed and closed for this: https://bugs.python.org/issue38342.

**Comment by asottile** [comment]
ahah, as I suspected -- unclean installs :)
