### ISSUE TITLE
unittest subTest() fail with --pdb (AttributeError: 'NoneType' object has no attribute 'result_supports_subtests')

### ISSUE THREAD

**Issue by philpep** [pytest-dev/pytest#2318]
Hi,

``pytest --pdb`` fail on a test suite using unittest ``subTest`` api.

Example (the bug occur in the same way in unittest2 and in python 3 unittest).

```python
import sys
if sys.version_info[0] == 2:
    import unittest2 as unittest
else:
    import unittest

class TC(unittest.TestCase):

    def test_subtest(self):
        with self.subTest():
            pass
```

```
% python -m pytest --pdb
t.py F
>>>>>> traceback >>>>>>

self = <t.TC testMethod=test_subtest>

    def test_subtest(self):
>       with self.subTest():

t.py:10: 
_ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/contextlib.py:17: in __enter__
    return self.gen.next()
E   AttributeError: 'NoneType' object has no attribute 'result_supports_subtests'
>>>>>>> entering PDB >>>>>>>
```

I know that pytest doesn't support this API and will raise on first error, but it always fail with ``--pdb``.

The bug has been introduced in #1890 since ``TestCase._outcome`` is not assigned with ``debug()``. Not sure how this should be fixed (maybe by finding another workaround for #1890 ?)

Thanks !

**Comment by nicoddemus** [comment]
https://github.com/python/cpython/pull/9707 👍

**Comment by philpep** [comment]
Awesome, thanks!!
