### ISSUE TITLE
Update from 4.0.2 to 4.1.0 broke all tests

### ISSUE THREAD

**Issue by CrimsonGlory** [pytest-dev/pytest#4610]
On circleci, inside python:2.7 image, all tests started to fail with the same error after update from pytest 4.0.2 to 4.1.0 (other modules installed are pytest-cov-2.6.0 pytest-timeout-1.3.3)
```
self = <pytest_cov.plugin.CovPlugin object at 0x7f20a78e6110>
item = <Function test_cg_1366>

    @compat.hookwrapper
    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
                or 'no_cover' in getattr(item, 'fixturenames', ())):
E               AttributeError: 'Function' object has no attribute 'get_marker'

/usr/local/lib/python2.7/site-packages/pytest_cov/plugin.py:289: AttributeError
```

**Comment by CrimsonGlory** [comment]
Seem this is fixed in pytest-cov repo and waiting to be released.
https://github.com/pytest-dev/pytest-cov/issues/254
https://github.com/pytest-dev/pytest-cov/pull/253

**Comment by Zac-HD** [comment]
And now released as `pytest-cov=2.6.1`
