### ISSUE TITLE
All test failed in 4.1.0

### ISSUE THREAD

**Issue by gukz** [pytest-dev/pytest#4611]
`pytest==4.1.0`
When I use the 4.0.1, everything is just Ok, but when I updated to 4.0.1, I got lots of error message looks like below, can anyone tell me what's wrong?
```
self = <pytest_cov.plugin.CovPlugin object at 0x7f640c201d30>
item = <Function test_crud_aditem>

    @compat.hookwrapper
    def pytest_runtest_call(self, item):
>       if (item.get_marker('no_cover')
                or 'no_cover' in getattr(item, 'fixturenames', ())):
E               AttributeError: 'Function' object has no attribute 'get_marker'

item       = <Function test_crud_aditem>
self       = <pytest_cov.plugin.CovPlugin object at 0x7f640c201d30>

venv/lib/python3.6/site-packages/pytest_cov/plugin.py:289: AttributeError
```

**Comment by cmclaughlin** [comment]
I have the same problem.

**Comment by prsolucoes** [comment]
Same problem :(

**Comment by jnd77** [comment]
Solved it by updating pytest-cov to 2.6.1

**Comment by RonnyPfannschmidt** [comment]
duplicate of #4610
