### ISSUE TITLE
After upgrading pytest from 6.2.5 to 7.0.1 test framework fails to run with error "cannot import name 'scopenum_function' from '_pytest.fixtures'"

### ISSUE THREAD

**Issue by MaximShteygervald** [pytest-dev/pytest#9718]
Setup:
Django project with pytest tests
- Django 4.0.1
- pytest 7.0.1
- pytest-django - 4.5.2
- pytest-mock - 3.7.0
- pytest-pycharm - 0.7.0
- python 3.9.9
- mac os - 12.2.1

Traceback of error:

> Traceback (most recent call last):
>   File "/Users/maximshteygervald/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/213.6777.50/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_pytest_runner.py", line 51, in <module>
>     sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 146, in main
>     config = _prepareconfig(args, plugins)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 325, in _prepareconfig
>     config = pluginmanager.hook.pytest_cmdline_parse(
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
>     return self._hookexec(self, self.get_hookimpls(), kwargs)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
>     return self._inner_hookexec(hook, methods, kwargs)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
>     gen.send(outcome)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/helpconfig.py", line 102, in pytest_cmdline_parse
>     config: Config = outcome.get_result()
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
>     raise ex[1].with_traceback(ex[2])
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
>     res = hook_impl.function(*args)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1013, in pytest_cmdline_parse
>     self.parse(args)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1301, in parse
>     self._preparse(args, addopts=addopts)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1184, in _preparse
>     self.pluginmanager.load_setuptools_entrypoints("pytest11")
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
>     plugin = ep.load()
>   File "/Users/maximshteygervald/.pyenv/versions/3.9.9/lib/python3.9/importlib/metadata.py", line 77, in load
>     module = import_module(match.group('module'))
>   File "/Users/maximshteygervald/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
>     exec(co, module.__dict__)
>   File "/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/pytest_fixture_order/plugin.py", line 3, in <module>
>     from _pytest.fixtures import scopenum_function
> ImportError: cannot import name 'scopenum_function' from '_pytest.fixtures' (/Users/maximshteygervald/Library/Caches/pypoetry/virtualenvs/django-4S23ZR49-py3.9/lib/python3.9/site-packages/_pytest/fixtures.py)
> 
> Process finished with exit code 1
> 
> Empty suite
> 
> Empty suite

Downgrading pytest to 6.2.5 fully solves the error. Tests start working as expected.

**Comment by bluetech** [comment]
Hi @MaximShteygervald,

This is an issue that needs to be fixed in the pytest-fixture-order plugin: https://github.com/theY4Kman/pytest-fixture-order/issues/2.
