### ISSUE TITLE
Exception when using pytest >= 5.0.0 with pypy3

### ISSUE THREAD

**Issue by texasaggie97** [pytest-dev/pytest#5807]
<!--
Thanks for submitting an issue!

Here's a quick checklist for what to provide:
-->

- [X] a detailed description of the bug or suggestion
- [X] output of `pip list` from the virtual environment you are using
- [X] pytest and operating system versions
- [ ] minimal example if possible

I am getting the following exception when using pytest with pypy3 (either pypy3.5 or pypy3.6):
```
INTERNALERROR> Traceback (most recent call last):                                                                                                                                                                                                                             INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\main.py", line 187, in wrap_session                                                                                                                              INTERNALERROR>     config._do_configure()                                                                                                                                                                                                                                     INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\config\__init__.py", line 704, in _do_configure                                                                                                                  INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))                                                                                                                                                                                         INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\hooks.py", line 311, in call_historic                                                                                                                             INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)                                                                                                                                                                                                   INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\manager.py", line 87, in _hookexec                                                                                                                                INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)                                                                                                                                                                                                         INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\manager.py", line 81, in <lambda>                                                                                                                                 INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                                                                                                                                                                                     INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 208, in _multicall                                                                                                                              INTERNALERROR>     return outcome.get_result()                                                                                                                                                                                                                                INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 80, in get_result                                                                                                                               INTERNALERROR>     raise ex[1].with_traceback(ex[2])                                                                                                                                                                                                                          INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 187, in _multicall                                                                                                                              INTERNALERROR>     res = hook_impl.function(*args)                                                                                                                                                                                                                            INTERNALERROR>   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\faulthandler.py", line 21, in pytest_configure                                                                                                                   INTERNALERROR>     if faulthandler.is_enabled():                                                                                                                                                                                                                              INTERNALERROR> AttributeError: module 'faulthandler' has no attribute 'is_enabled'                                                                                                                                                                                            Traceback (most recent call last):                                                                                                                                                                                                                                              File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\py\test.py", line 4, in <module>                                                                                                                                                            sys.exit(pytest.main())                                                                                                                                                                                                                                                     File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\config\__init__.py", line 78, in main                                                                                                                                               return config.hook.pytest_cmdline_main(config=config)                                                                                                                                                                                                                       File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\hooks.py", line 289, in __call__                                                                                                                                                     return self._hookexec(self, self.get_hookimpls(), kwargs)                                                                                                                                                                                                                   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\manager.py", line 87, in _hookexec                                                                                                                                                   return self._inner_hookexec(hook, methods, kwargs)                                                                                                                                                                                                                          File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\manager.py", line 81, in <lambda>                                                                                                                                                    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,                                                                                                                                                                                                      File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 208, in _multicall                                                                                                                                                 return outcome.get_result()                                                                                                                                                                                                                                                 File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 80, in get_result                                                                                                                                                  raise ex[1].with_traceback(ex[2])                                                                                                                                                                                                                                           File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 187, in _multicall                                                                                                                                                 res = hook_impl.function(*args)                                                                                                                                                                                                                                             File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\main.py", line 228, in pytest_cmdline_main                                                                                                                                          return wrap_session(config, _main)                                                                                                                                                                                                                                          File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\main.py", line 223, in wrap_session                                                                                                                                                 config._ensure_unconfigure()                                                                                                                                                                                                                                                File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\config\__init__.py", line 709, in _ensure_unconfigure                                                                                                                               self.hook.pytest_unconfigure(config=self)                                                                                                                                                                                                                                   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\hooks.py", line 289, in __call__                                                                                                                                                     return self._hookexec(self, self.get_hookimpls(), kwargs)                                                                                                                                                                                                                   File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\msilva\documents\github\nimi-python\.tox\64\pypy3-test\site-packages\_pytest\faulthandler.py", line 42, in pytest_unconfigure
    faulthandler.disable()
AttributeError: module 'faulthandler' has no attribute 'disable'
```

This same configuration works with cpython 3.4 - 3.7

I am not able to get around this by using `-p no:faulthandler`. It looks like this error is happening before that can take affect.

```
Package            Version
------------------ -------
atomicwrites       1.3.0
attrs              19.1.0
cffi               1.12.0
colorama           0.4.1
coverage           4.5.4
greenlet           0.4.13
importlib-metadata 0.19
Mako               1.1.0
MarkupSafe         1.1.1
mock               3.0.5
more-itertools     7.2.0
numpy              1.17.1
packaging          19.1
pathlib2           2.3.4
pip                19.2.3
pluggy             0.12.0
py                 1.8.0
pyparsing          2.4.2
pytest             5.1.2
readline           6.2.4.1
setuptools         41.2.0
six                1.12.0
wcwidth            0.1.7
wheel              0.33.6
zipp               0.6.0
```

I have tried this with pytest 5.0.0, 5.0.1, 5.1.1 and 5.1.2 and am seeing this on Windows 10 and Linux (via Travis CI)

You can see an example of this at this build: https://travis-ci.org/ni/nimi-python/jobs/578577545

**Comment by asottile** [comment]
pypy 5.10 is pretty old -- have you tried with a newer version?

the `faulthandler` module is functional for me in pypy3.6:

```console
$ pypy3 -c 'import sys; print(sys.version); import faulthandler; print(faulthandler.is_enabled())'
3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901]
False
```

**Comment by texasaggie97** [comment]
I am using the latest of pypy3.5 (7.0.0) and pypy3.6 (7.1.1)

```
pypy3 -c 'import sys; print(sys.version); import faulthandler; print(faulthandler.is_enabled())'
3.5.3 (928a4f70d3de, Feb 08 2019, 12:56:35)
[PyPy 7.0.0 with MSC v.1910 32 bit]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'faulthandler' has no attribute 'is_enabled'
```

```
[C:\pypy3.6-v7.1.1-win32]pypy3 -c "import sys; print(sys.version); import faulthandler; print(faulthandler.is_enabled())"
3.6.1 (784b254d6699, Apr 16 2019, 12:10:48)
[PyPy 7.1.1-beta0 with MSC v.1910 32 bit]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'faulthandler' has no attribute 'is_enabled'
```

**Comment by The-Compiler** [comment]
What does `pypy3 -c 'import faulthandler; print(faulthandler.__file__)'` say?

Can't check right now, but there I'd expect an `AttributeError` because it's a C module.

**Comment by texasaggie97** [comment]
```
[C:\pypy3.6-v7.1.1-win32]pypy3 -c "import faulthandler; print(faulthandler.__file__)"
C:\pypy3.6-v7.1.1-win32\lib_pypy\faulthandler.py
```

This is the contents of this file:
``` python
# This is only imported for platforms where the built-in faulthandler module is not 
# available.  It provides no function at all so far, but it is enough to start the
# CPython test suite.

def enable(*args, **kwargs):
    pass

def register(*args, **kwargs):
    pass
```

**Comment by asottile** [comment]
I went to reproduce this and hit a different error with pypy3 on windows (which appears fixed in the latest nightly) 🤔

After upgrading to the latest nightly of pypy3.6, the problem in this issue is gone (more of `faulthandler` is stubbed)

Is using the latest nightly an option for you?

**Comment by texasaggie97** [comment]
> Is using the latest nightly an option for you?

I am at the mercy of Travis CI and when they make newer builds available. However, I have a workaround in place, so if you want to close this I think that would be fine.

**Comment by nicoddemus** [comment]
Thanks @texasaggie97!
